export const INDEX_LIST = 'INDEX_LIST';//首页数据
export const TAB_CHANGE = 'TAB_CHANGE';//TAB切换
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL';//文章详情
export const DOWN_LOAD = 'DOWN_LOAD';//下拉图标控制
export const CHECK_TOKEN = 'CHECK_TOKEN' // 检查token
export const TOAST = 'TOAST'; // 吐司
export const REPLY_TOPIC = 'REPLY_TOPIC'; // 评论
export const UPS_TOPIC = 'UPS_TOPIC'; // topic 点赞
export const GET_TOPIC_DETAIL = 'GET_TOPIC_DETAIL'; // 获取文章详情
export const UP_REPLY = 'UP_REPLY'; // 评论点赞
export const GET_PHOTO = 'GET_PHOTO'; // 照片列表
export const GET_VIDEO = 'GET_VIDEO'; // 视频列表
export const GET_VIDEO_START = 'GET_VIDEO_START'; // 开始请求视频列表
export const LOGOUT = 'LOGOUT' ; // 退出
export const CLEAR_CACHE_DETAIL = 'CLEAR_CACHE_DETAIL' // 清除文章缓存
